controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 0.5
    publish_rate: 50.0

    base_frame_id: base_link
    odom_frame_id: odom
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    # Required joints
    # front_wheel_names: ["front_left_wheel_joint", "front_right_wheel_joint"]
    rear_wheel_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    front_steering_names: ["front_left_steering_joint", "front_right_steering_joint"]

    wheelbase: 3.8  # distance between front and rear axles [m]
    front_wheel_track: 2.2  # distance between front left and right wheels [m]
    rear_wheel_track: 2.2   # usually same as front for symmetry
    front_wheels_radius: 0.28
    rear_wheels_radius: 0.28

    open_loop: true
    enable_odom_tf: true
    use_stamped_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 1.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 1.0
