controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_controller_velocity:
      type: ackermann_steering_controller/AckermannSteeringController
    
    front_wheel_data:
      type: velocity_controllers/JointGroupVelocityController



ackermann_controller_velocity:
  ros__parameters:
    wheelbase: 3.8  # distance between front and rear axles [m]
    front_wheel_track: 2.2  # distance between front left and right wheels [m]
    rear_wheel_track: 2.2   # usually same as front for symmetry
    front_wheels_radius: 0.28
    rear_wheels_radius: 0.28
    front_steering: true
    reference_timeout: 2.0
    publish_rate: 70.0
    rear_wheels_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    front_wheels_names: ["front_left_steering_joint", "front_right_steering_joint"]
    use_stamped_vel: true
    open_loop: false
    velocity_rolling_window_size: 10
    # max_steering_angle: 0.785  # 45 degrees in radians
    # min_steering_angle: -0.785
    publish_odom: true
    base_frame_id: base_link
    odom_frame_id: odom
    pose_covariance_diagonal: [0.01, 0.01, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.01, 0.0, 0.0, 0.0, 0.0, 0.01]
    enable_odom_tf: true
    position_feedback: true
    # wheel_separation: 1.0
    # cmd_vel_topic: "cmd_vel_ack_stamped"
    # cmd_type: "geometry_msgs/msg/TwistStamped"

front_wheel_data:
  ros__parameters:
    joint:
      - front_left_wheel_joint
      - front_right_wheel_joint
    state_interface_names:
      - velocity
      - position
    
