controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_controller_velocity:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_controller_velocity:
  ros__parameters:
    reference_timeout: 2.0
    publish_rate: 100.0
    position_feedback: true
    velocity_feedback: true
    steering_feedback: true
    front_wheel_names: ["front_left_wheel_joint", "front_right_wheel_joint"]
    traction_wheel_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    steering_wheel_names: ["front_left_steering_joint", "front_right_steering_joint"]
    
    # Joint interfaces
    front_wheels_joint_interfaces: ["velocity"]
    traction_wheels_joint_interfaces: ["velocity"]
    steering_wheels_joint_interfaces: ["position"]
    base_frame_id: base_link
    odom_frame_id: odom

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    wheelbase: 3.8  # distance between front and rear axles [m]
    front_wheel_track: 2.2  # distance between front left and right wheels [m]
    rear_wheel_track: 2.2   # usually same as front for symmetry
    front_wheels_radius: 0.28
    rear_wheels_radius: 0.28
    wheel_separation_multiplier: 1.0
  
    open_loop: true
    enable_odom_tf: true
    use_stamped_vel: false
    enable_odom_tf: true

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 1.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 1.0
    cmd_vel_timeout: 0.5
