naor_drone:
  mac_adress: [0x04, 0xE9, 0xE5, 0x18, 0xEE, 0x80]

config_teensy:
  mac_adress: [0x04, 0xE9, 0xE5, 0x18, 0xEE, 0xFC]

amit_drone:
  mac_adress: [0x04, 0xE9, 0xE5, 0x19, 0x2B, 0x2D]

last_drone:
  mac_adress: [0x04, 0xE9, 0xE5, 0x17, 0xE3, 0x91]







