slam_toolbox:
  ros__parameters:
    # General Parameters
    use_sim_time: true
    slam_mode: true
    map_file_name: ""  # No preloaded map
    resolution: 0.05  # Map resolution in meters per cell
    max_laser_range: 20.0  # Increase max laser range for larger maps
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 20  # Increased from default 10
    scan_buffer_maximum_scan_distance: 20.0  # Increased for larger mapping

    # Loop Closure Parameters
    enable_interactive_mode: false
    loop_search_space_dimension: 20.0  # Increased search space for large maps
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 5.0
    loop_match_minimum_response_coarse: 0.5
    loop_match_minimum_response_fine: 0.8

    # Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.03
    link_match_minimum_response_fine: 0.8
    link_match_minimum_response_coarse: 0.5

    # Advanced Map Building Parameters
    max_map_size: 2000  # Very large map size in pixels - increase for bigger maps
    stack_size_to_use: 60000000  # Increased memory allocation for larger maps
    publish_map: true
    publish_pose: true
    publish_odom: true
    laser_scan_topic: /scan
    odom_frame: odom
    odom_topic: /odometry/filtered
    base_frame: base_link
    map_frame: map

    
    # For real-world drift compensation
    fine_search_angle_offset: 0.00349  # Increase angle search space
    coarse_search_angle_offset: 0.349  # Increase angle search space
    transform_timeout: 0.3  # Larger timeout for odometry
    map_update_interval: 5.0  # Update map less frequently to handle larger maps 