---

controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    propellors:
      type: effort_controllers/JointGroupEffortController

propellors:
  ros__parameters:
    joints:
      - A_prop_joint
      - B_prop_joint
      - C_prop_joint
      - D_prop_joint
      - E_prop_joint
      - F_prop_joint
      - G_prop_joint
      - H_prop_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

