---

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    propeller_controllers:
      type: velocity_controllers/JointGroupVelocityController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

propeller_controllers:
  ros__parameters:
    joints:
      - base_front_right_propeller_joint
      - base_front_left_propeller_joint
      - base_back_right_propeller_joint
      - base_back_left_propeller_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity
      - effort

imu_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: base_link